### ISSUE TITLE
Do no check in email credentials to the git

### ISSUE THREAD

**Issue by avinassh** [deadcoder0904/subscription-newsletter#2]
this line is trouble:

https://github.com/deadcoder0904/subscription-newsletter/blob/master/index.js#L5

You shouldn't make your login credentials public.

And also, if that excel sheet is public, then anyone can spam the people who have subscribed.

**Comment by deadcoder0904** [comment]
Duplicate #1.

Also, I can make it private too so no one can edit it. For more info, check https://github.com/dwyl/html-form-send-email-via-google-script-without-server
